// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhcxctxwwSgHZTXfO1P6OLxYmu9W3xvk',
    appId: '1:561640821892:web:0d74e699e63d13548dded1',
    messagingSenderId: '561640821892',
    projectId: 'toolapp-3e6c5',
    authDomain: 'toolapp-3e6c5.firebaseapp.com',
    storageBucket: 'toolapp-3e6c5.firebasestorage.app',
    measurementId: 'G-H30YCFXCZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcRUOwJN9yxAC01bSINEIuQLNCzAHm88I',
    appId: '1:561640821892:android:50226f9ab410db2a8dded1',
    messagingSenderId: '561640821892',
    projectId: 'toolapp-3e6c5',
    storageBucket: 'toolapp-3e6c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg0a9cFDvbWJt7-iccCRma0m--gf4Q4h0',
    appId: '1:561640821892:ios:f5028d081f9f45c08dded1',
    messagingSenderId: '561640821892',
    projectId: 'toolapp-3e6c5',
    storageBucket: 'toolapp-3e6c5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg0a9cFDvbWJt7-iccCRma0m--gf4Q4h0',
    appId: '1:561640821892:ios:f5028d081f9f45c08dded1',
    messagingSenderId: '561640821892',
    projectId: 'toolapp-3e6c5',
    storageBucket: 'toolapp-3e6c5.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdhcxctxwwSgHZTXfO1P6OLxYmu9W3xvk',
    appId: '1:561640821892:web:d3c9f419496f38958dded1',
    messagingSenderId: '561640821892',
    projectId: 'toolapp-3e6c5',
    authDomain: 'toolapp-3e6c5.firebaseapp.com',
    storageBucket: 'toolapp-3e6c5.firebasestorage.app',
    measurementId: 'G-C634MDVKZR',
  );
}
